# Generated by Django 6.0 on 2025-12-19 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_medicalreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('facility_type', models.CharField(max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'facilities',
            },
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='past_history',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('test_value', models.FloatField()),
                ('test_unit', models.CharField(max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=100)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('medical_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='api.medicalreport')),
            ],
            options={
                'db_table': 'medical_tests',
            },
        ),
        migrations.CreateModel(
            name='AbnormalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('concern_level', models.CharField(max_length=20)),
                ('interpretation', models.TextField()),
                ('medical_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_result', to='api.medicaltest')),
            ],
            options={
                'db_table': 'abnormal_results',
            },
        ),
        migrations.CreateModel(
            name='TriageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_symptoms', models.TextField()),
                ('input_mode', models.CharField(default='text', max_length=20)),
                ('voice_file', models.FileField(blank=True, null=True, upload_to='voice_recordings/%Y/%m/%d/')),
                ('risk_level', models.CharField(choices=[('emergency', 'Emergency'), ('high', 'High Risk'), ('medium', 'Medium Risk'), ('low', 'Low Risk')], max_length=20)),
                ('risk_probability', models.FloatField(default=0.0)),
                ('reasoning', models.TextField()),
                ('confidence', models.FloatField(default=0.0)),
                ('assessment_source', models.CharField(default='ai', max_length=50)),
                ('similar_cases', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.medicalreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Triage Record',
                'verbose_name_plural': 'Triage Records',
                'db_table': 'triage_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('action', 'Action'), ('dietary', 'Dietary'), ('lifestyle', 'Lifestyle'), ('medication', 'Medication'), ('facility', 'Facility Visit')], max_length=20)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(default=1)),
                ('triage_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.triagerecord')),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='PossibleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('triage_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_conditions', to='api.triagerecord')),
            ],
            options={
                'db_table': 'possible_conditions',
                'ordering': ['-confidence'],
            },
        ),
    ]
