# Generated by Django 4.2.27 on 2026-03-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_medicalreport_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalreport",
            name="status",
        ),
    ]
