# Generated by Django 4.2.27 on 2026-07-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_dietaryadvice"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalreport",
            name="insights_text",
            field=models.TextField(
                blank=True,
                help_text="LLM-generated narrative insight for the report",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="medicalreport",
            name="ocr_path",
            field=models.CharField(
                blank=True,
                help_text="Which OCR path served: apple_vision, tesseract, nvidia_vision",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="medicalreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
