# Generated by Django 4.2.27 on 2026-07-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_medicalreport_insights_text_medicalreport_ocr_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="other_notes",
            field=models.TextField(
                blank=True,
                help_text="Free-text field for allergies, surgeries, family history, medications, etc.",
                max_length=2000,
                null=True,
            ),
        ),
    ]
