# Generated by Django 4.2.27 on 2026-07-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_userprofile_other_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="triagerecord",
            name="requires_human_review",
            field=models.BooleanField(
                default=False,
                help_text="Set when the assessment is degraded, low-confidence, or otherwise needs clinician follow-up.",
            ),
        ),
    ]
