# Generated by Django 4.2.27 on 2026-07-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_triagerecord_requires_human_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="preferred_language",
        ),
    ]
