# Generated by Django 5.2.4 on 2025-12-21 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_facility_medicalreport_extracted_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("symptoms", "Initial Symptoms"),
                            ("history", "Medical History"),
                            ("questions", "Clarifying Questions"),
                            ("assessment", "AI Assessment"),
                            ("results", "Final Results"),
                            ("completed", "Completed"),
                        ],
                        default="symptoms",
                        max_length=20,
                    ),
                ),
                ("symptoms", models.TextField(blank=True, null=True)),
                ("medical_history", models.JSONField(blank=True, default=dict)),
                ("clarifying_questions", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "triage_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultation_session",
                        to="api.triagerecord",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation Session",
                "verbose_name_plural": "Consultation Sessions",
                "db_table": "consultation_sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
