"""
Django settings for medaid project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from environment in production; fall back to a dev-only placeholder.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-local-dev-secret')

# SECURITY WARNING: don't run with debug turned on in production!
# Controlled via environment; set DJANGO_DEBUG='False' in production.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').strip().lower() in {'1', 'true', 'yes', 'on'}

if not DEBUG and SECRET_KEY.startswith('django-insecure-'):
    raise RuntimeError('DJANGO_SECRET_KEY must be configured when DJANGO_DEBUG is disabled.')

def _csv_env(name, default):
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


# Restrict allowed hosts by default. In production, set via environment.
ALLOWED_HOSTS = _csv_env('ALLOWED_HOSTS', 'localhost,127.0.0.1')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'medaid.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medaid.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

_db_engine = os.environ.get('DB_ENGINE', '').strip().lower()
_db_name = os.environ.get('DB_NAME')
_db_user = os.environ.get('DB_USER')
_db_password = os.environ.get('DB_PASSWORD')
_db_host = os.environ.get('DB_HOST')
_db_port = os.environ.get('DB_PORT')

# DB_ENGINE must be stated explicitly. This block previously ended in an
# unconditional `else` that fell back to SQLite, so an environment carrying a
# full set of PostgreSQL credentials would read them, discard them, and run on
# a local SQLite file without ever saying so. An unset or unrecognised value is
# now a startup error rather than a silent downgrade.
_POSTGRES_ALIASES = {'postgres', 'postgresql'}
_SQLITE_ALIASES = {'sqlite', 'sqlite3'}
_VALID_DB_ENGINES = ', '.join(sorted(_POSTGRES_ALIASES | _SQLITE_ALIASES))

if not _db_engine:
    raise ImproperlyConfigured(
        'DB_ENGINE is not set. Set it explicitly to one of: '
        f'{_VALID_DB_ENGINES}. There is no default -- an unset DB_ENGINE '
        'previously fell back to SQLite silently, which hid misconfigured '
        'PostgreSQL deployments.'
    )

if _db_engine in _POSTGRES_ALIASES:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _db_name or 'medaid_db',
            'USER': _db_user or 'postgres',
            'PASSWORD': _db_password or 'postgres',
            'HOST': _db_host or 'localhost',
            'PORT': _db_port or '5432',
        }
    }
elif _db_engine in _SQLITE_ALIASES:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    raise ImproperlyConfigured(
        f'DB_ENGINE={_db_engine!r} is not a recognised value. '
        f'Use one of: {_VALID_DB_ENGINES}.'
    )


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Deployment security defaults. Local development remains HTTP-friendly; a
# production deployment must provide DJANGO_DEBUG=False and use HTTPS.
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False' if DEBUG else 'True').strip().lower() in {'1', 'true', 'yes', 'on'}
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True' if not DEBUG else 'False').strip().lower() in {'1', 'true', 'yes', 'on'}
SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'True' if not DEBUG else 'False').strip().lower() in {'1', 'true', 'yes', 'on'}
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'True' if not DEBUG else 'False').strip().lower() in {'1', 'true', 'yes', 'on'}
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'True' if not DEBUG else 'False').strip().lower() in {'1', 'true', 'yes', 'on'}
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if not DEBUG else None


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploads)
import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

# CORS Configuration. Production must set CORS_ALLOWED_ORIGINS to the deployed
# frontend origin(s); local development keeps the common React/Django ports.
_local_frontend_origins = 'http://localhost:8000,http://127.0.0.1:8000,http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001'
CORS_ALLOWED_ORIGINS = _csv_env(
    'CORS_ALLOWED_ORIGINS',
    _local_frontend_origins if DEBUG else '',
)

CORS_ALLOW_CREDENTIALS = True

# Email Configuration (for future use)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Default auto field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'api.User'

# Cache settings. Set REDIS_URL in production so global quota throttles are
# shared across workers. Local/test environments default to in-process cache.
REDIS_URL = os.environ.get("REDIS_URL", "")
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "medaid-local-cache",
        }
    }
    if not DEBUG:
        # LocMemCache is per-process, so with N gunicorn/uwsgi workers the
        # shared free-tier quotas are silently enforced N times over. Surface
        # that loudly rather than letting it be discovered via a provider ban.
        import logging as _logging

        _logging.getLogger(__name__).warning(
            "cache.redis_unconfigured_in_production REDIS_URL is not set: rate "
            "limits and quotas are enforced PER PROCESS, not globally. With "
            "multiple workers the effective limits are multiplied by the worker "
            "count. Set REDIS_URL to enforce them across workers."
        )

# Celery Configuration Options
CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 200000  # 200MB

# Periodic jobs. The OpenRouter failover-model cache is warmed here rather
# than inside assess(), so a slow /models endpoint can never add latency to a
# patient's triage request. Runs at half the 1h cache TTL so one missed run
# still leaves the cache warm.
CELERY_BEAT_SCHEDULE = {
    'refresh-openrouter-fallback-model': {
        'task': 'api.tasks.refresh_openrouter_fallback_model_task',
        'schedule': 30 * 60,  # every 30 minutes
    },
}

# LLM provider configuration for the main V2 triage engine.
OPENROUTER_API_KEY = os.environ.get('OPENROUTER_API_KEY', '')
OPENROUTER_BASE_URL = os.environ.get('OPENROUTER_BASE_URL', 'https://openrouter.ai/api/v1')
OPENROUTER_HTTP_REFERER = os.environ.get('OPENROUTER_HTTP_REFERER', 'http://localhost:3000')
OPENROUTER_APP_TITLE = os.environ.get('OPENROUTER_APP_TITLE', 'MedAid')
OPENROUTER_MODEL_CACHE_SECONDS = int(os.environ.get('OPENROUTER_MODEL_CACHE_SECONDS', 60 * 60 * 4))
DEFAULT_TRIAGE_MODEL = os.environ.get('DEFAULT_TRIAGE_MODEL', 'gemini-3.1-flash-lite')
TRIAGE_MODEL_TEMPERATURE = float(os.environ.get('TRIAGE_MODEL_TEMPERATURE', 0.4))
# LAST-RESORT cross-provider failover target. The live free-model catalog is
# queried first (see llm_providers.catalog.resolve_fallback_openrouter_model,
# cached hourly); this value is only used if that lookup fails or returns no
# zero-cost models. Set to '' to disable failover to OpenRouter entirely.
#
# MUST be a free (zero-cost) model: this is a failover target that can fire
# without any user opt-in, so a paid id here silently bills on every Gemini
# outage. MUST also support response_format=json_object, since
# OpenRouterProvider always requests structured JSON - a model without it 400s.
# google/gemma-4-31b-it:free satisfies both and is the closest free analogue to
# the Gemini flash primary it backs up (262k context for history-carrying
# triage prompts).
TRIAGE_FALLBACK_OPENROUTER_MODEL = os.environ.get(
    'TRIAGE_FALLBACK_OPENROUTER_MODEL', 'google/gemma-4-31b-it:free'
)
DIETARY_DEFAULT_FREE_MODEL = os.environ.get('DIETARY_DEFAULT_FREE_MODEL', '')
DIETARY_MODEL_TEMPERATURE = float(os.environ.get('DIETARY_MODEL_TEMPERATURE', 0.25))
DIETARY_THROTTLE_SECONDS = int(os.environ.get('DIETARY_THROTTLE_SECONDS', 15))
DIETARY_ACTIVE_REQUEST_SECONDS = int(os.environ.get('DIETARY_ACTIVE_REQUEST_SECONDS', 120))
DIETARY_GLOBAL_RPM_LIMIT = int(os.environ.get('DIETARY_GLOBAL_RPM_LIMIT', 18))
DIETARY_GLOBAL_DAILY_LIMIT = int(os.environ.get('DIETARY_GLOBAL_DAILY_LIMIT', 45))
DIETARY_GLOBAL_ACTIVE_LIMIT = int(os.environ.get('DIETARY_GLOBAL_ACTIVE_LIMIT', 2))

# ---------------------------------------------------------------------------
# Per-endpoint LLM quota ceilings (see api/llm_quota.py).
#
# STARTING ESTIMATES to be tuned against real usage data - NOT measured values.
# Each endpoint has a global ceiling (shared, app-wide) and a per-user ceiling
# (so one user can't exhaust the shared quota for everyone). Both are enforced
# PER PROCESS via LocMemCache when REDIS_URL is unset - the same caveat the
# cache block above already warns about - so with N workers each ceiling is
# effectively multiplied by N. Set REDIS_URL to enforce them across workers.
# ---------------------------------------------------------------------------
TRIAGE_GLOBAL_RPM_LIMIT = int(os.environ.get('TRIAGE_GLOBAL_RPM_LIMIT', 18))
TRIAGE_GLOBAL_DAILY_LIMIT = int(os.environ.get('TRIAGE_GLOBAL_DAILY_LIMIT', 45))
TRIAGE_USER_RPM_LIMIT = int(os.environ.get('TRIAGE_USER_RPM_LIMIT', 5))
TRIAGE_USER_DAILY_LIMIT = int(os.environ.get('TRIAGE_USER_DAILY_LIMIT', 15))

CHAT_GLOBAL_RPM_LIMIT = int(os.environ.get('CHAT_GLOBAL_RPM_LIMIT', 30))
CHAT_GLOBAL_DAILY_LIMIT = int(os.environ.get('CHAT_GLOBAL_DAILY_LIMIT', 100))
CHAT_USER_RPM_LIMIT = int(os.environ.get('CHAT_USER_RPM_LIMIT', 10))
CHAT_USER_DAILY_LIMIT = int(os.environ.get('CHAT_USER_DAILY_LIMIT', 30))

REPORT_INSIGHT_GLOBAL_RPM_LIMIT = int(os.environ.get('REPORT_INSIGHT_GLOBAL_RPM_LIMIT', 18))
REPORT_INSIGHT_GLOBAL_DAILY_LIMIT = int(os.environ.get('REPORT_INSIGHT_GLOBAL_DAILY_LIMIT', 45))
REPORT_INSIGHT_USER_RPM_LIMIT = int(os.environ.get('REPORT_INSIGHT_USER_RPM_LIMIT', 5))
REPORT_INSIGHT_USER_DAILY_LIMIT = int(os.environ.get('REPORT_INSIGHT_USER_DAILY_LIMIT', 15))

# OCR service configuration (Apple Vision OCR microservice on macOS)
OCR_SERVICE_URL = os.environ.get('OCR_SERVICE_URL', 'http://127.0.0.1:5050')
OCR_SERVICE_KEY = os.environ.get('OCR_SERVICE_KEY', '')
OCR_SERVICE_TIMEOUT = int(os.environ.get('OCR_SERVICE_TIMEOUT', 20))

# Report insight generation model
REPORT_INSIGHT_MODEL = os.environ.get('REPORT_INSIGHT_MODEL', 'gemini-2.5-flash')
REPORT_INSIGHT_TEMPERATURE = float(os.environ.get('REPORT_INSIGHT_TEMPERATURE', 0.2))

# User-selectable OpenRouter models. Free-tier by default so no user choice
# silently bills. Every id here MUST support response_format=json_object (the
# provider always requests structured JSON) and be zero-cost. To offer a paid
# model as an EXPLICIT opt-in, add its id here AND a fallback-catalog entry
# with its real (non-zero) pricing - the model selector renders that pricing
# as a "Paid" tier so the cost is visible before selection, never silent.
ALLOWED_OPENROUTER_MODELS = [
    'google/gemma-4-31b-it:free',
    'nvidia/nemotron-3-super-120b-a12b:free',
    'openai/gpt-oss-20b:free',
]

# Metadata used to render the selector when OpenRouter's live /models endpoint
# is unreachable. Pricing here drives the Free/Paid tier badge, so it must
# match the model's real pricing: zero for the free ids above. A missing entry
# defaults to null pricing, which _is_free_pricing treats as PAID - so any id
# in ALLOWED_OPENROUTER_MODELS must have a row here to avoid a free model being
# mislabelled Paid during a catalog outage.
OPENROUTER_MODEL_FALLBACK_CATALOG = {
    'google/gemma-4-31b-it:free': {
        'name': 'Gemma 4 31B (free)',
        'context_length': 262144,
        'pricing': {'prompt': '0', 'completion': '0'},
        'description': 'Google instruction-tuned model with structured JSON output, free tier.',
    },
    'nvidia/nemotron-3-super-120b-a12b:free': {
        'name': 'Nemotron 3 Super 120B (free)',
        'context_length': 262144,
        'pricing': {'prompt': '0', 'completion': '0'},
        'description': 'NVIDIA reasoning-oriented MoE model with structured JSON output, free tier.',
    },
    'openai/gpt-oss-20b:free': {
        'name': 'GPT-OSS 20B (free)',
        'context_length': 131072,
        'pricing': {'prompt': '0', 'completion': '0'},
        'description': 'OpenAI open-weight model optimized for structured output, free tier.',
    },
}
