# Generated by Django 5.2.4 on 2025-12-21 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_consultationsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("clinician", "Clinician"),
                    ("admin", "Admin"),
                ],
                default="patient",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PatientAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("monitoring", "Under Monitoring"),
                            ("resolved", "Resolved"),
                            ("transferred", "Transferred"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=1)),
                ("notes", models.TextField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clinician",
                    models.ForeignKey(
                        limit_choices_to={"role": "clinician"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"role": "patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinician_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "triage_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="api.triagerecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Assignment",
                "verbose_name_plural": "Patient Assignments",
                "db_table": "patient_assignments",
                "ordering": ["priority", "-assigned_at"],
                "unique_together": {("patient", "triage_record", "clinician")},
            },
        ),
        migrations.CreateModel(
            name="ClinicianNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("is_private", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinician",
                    models.ForeignKey(
                        limit_choices_to={"role": "clinician"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinician_notes",
                        to="api.patientassignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinician Note",
                "verbose_name_plural": "Clinician Notes",
                "db_table": "clinician_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClinicianAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("new_emergency", "New Emergency Assessment"),
                            ("high_risk", "High Risk Patient"),
                            ("deteriorating", "Patient Condition Deteriorating"),
                            ("follow_up", "Follow-up Required"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("is_actioned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("actioned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clinician",
                    models.ForeignKey(
                        limit_choices_to={"role": "clinician"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"role": "patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="api.patientassignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinician Alert",
                "verbose_name_plural": "Clinician Alerts",
                "db_table": "clinician_alerts",
                "ordering": ["-created_at"],
            },
        ),
    ]
