# Generated by Django 4.2.27 on 2026-03-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalreport",
            name="status",
            field=models.CharField(default="processing", max_length=20),
        ),
    ]
